alter table FINALPROJECT_AUTO_PRODUCER add constraint FK_FINALPROJECT_AUTO_PRODUCER_COUNTRY foreign key (COUNTRY_ID) references FINALPROJECT_COUNTRY(ID);
create unique index IDX_FINALPROJECT_AUTO_PRODUCER_UK_NAME on FINALPROJECT_AUTO_PRODUCER (NAME) where DELETE_TS is null ;
create unique index IDX_FINALPROJECT_AUTO_PRODUCER_UK_CODE on FINALPROJECT_AUTO_PRODUCER (CODE) where DELETE_TS is null ;
create index IDX_FINALPROJECT_AUTO_PRODUCER_COUNTRY on FINALPROJECT_AUTO_PRODUCER (COUNTRY_ID);
