alter table SEC_USER add constraint FK_SEC_USER_DEFAULT_COUNTRY foreign key (DEFAULT_COUNTRY_ID) references FINALPROJECT_COUNTRY(ID);
create index IDX_SEC_USER_DEFAULT_COUNTRY on SEC_USER (DEFAULT_COUNTRY_ID);
