-- begin FINALPROJECT_AUTO_PRODUCER
alter table FINALPROJECT_AUTO_PRODUCER add constraint FK_FINALPROJECT_AUTO_PRODUCER_COUNTRY foreign key (COUNTRY_ID) references FINALPROJECT_COUNTRY(ID)^
create unique index IDX_FINALPROJECT_AUTO_PRODUCER_UK_NAME on FINALPROJECT_AUTO_PRODUCER (NAME) where DELETE_TS is null ^
create unique index IDX_FINALPROJECT_AUTO_PRODUCER_UK_CODE on FINALPROJECT_AUTO_PRODUCER (CODE) where DELETE_TS is null ^
create index IDX_FINALPROJECT_AUTO_PRODUCER_COUNTRY on FINALPROJECT_AUTO_PRODUCER (COUNTRY_ID)^
-- end FINALPROJECT_AUTO_PRODUCER
-- begin FINALPROJECT_COLOR
create unique index IDX_FINALPROJECT_COLOR_UK_CODE on FINALPROJECT_COLOR (CODE) where DELETE_TS is null ^
create unique index IDX_FINALPROJECT_COLOR_UK_NAME on FINALPROJECT_COLOR (NAME) where DELETE_TS is null ^
-- end FINALPROJECT_COLOR
-- begin SEC_USER
alter table SEC_USER add constraint FK_SEC_USER_DEFAULT_COUNTRY foreign key (DEFAULT_COUNTRY_ID) references FINALPROJECT_COUNTRY(ID)^
create index IDX_SEC_USER_DEFAULT_COUNTRY on SEC_USER (DEFAULT_COUNTRY_ID)^
-- end SEC_USER
-- begin FINALPROJECT_VEHICLE_MODEL
alter table FINALPROJECT_VEHICLE_MODEL add constraint FK_FINALPROJECT_VEHICLE_MODEL_PRODUCER foreign key (PRODUCER_ID) references FINALPROJECT_AUTO_PRODUCER(ID)^
create index IDX_FINALPROJECT_VEHICLE_MODEL_PRODUCER on FINALPROJECT_VEHICLE_MODEL (PRODUCER_ID)^
-- end FINALPROJECT_VEHICLE_MODEL
-- begin FINALPROJECT_VEHICLE_COMPLECTATION
alter table FINALPROJECT_VEHICLE_COMPLECTATION add constraint FK_FINALPROJECT_VEHICLE_COMPLECTATION_VEHICLE_MODEL foreign key (VEHICLE_MODEL_ID) references FINALPROJECT_VEHICLE_MODEL(ID)^
create index IDX_FINALPROJECT_VEHICLE_COMPLECTATION_VEHICLE_MODEL on FINALPROJECT_VEHICLE_COMPLECTATION (VEHICLE_MODEL_ID)^
-- end FINALPROJECT_VEHICLE_COMPLECTATION
-- begin FINALPROJECT_VEHICLE
alter table FINALPROJECT_VEHICLE add constraint FK_FINALPROJECT_VEHICLE_PRODUCER foreign key (PRODUCER_ID) references FINALPROJECT_AUTO_PRODUCER(ID)^
alter table FINALPROJECT_VEHICLE add constraint FK_FINALPROJECT_VEHICLE_MODEL foreign key (MODEL_ID) references FINALPROJECT_VEHICLE_MODEL(ID)^
alter table FINALPROJECT_VEHICLE add constraint FK_FINALPROJECT_VEHICLE_COMPLECTATION foreign key (COMPLECTATION_ID) references FINALPROJECT_VEHICLE_COMPLECTATION(ID)^
create index IDX_FINALPROJECT_VEHICLE_PRODUCER on FINALPROJECT_VEHICLE (PRODUCER_ID)^
create index IDX_FINALPROJECT_VEHICLE_MODEL on FINALPROJECT_VEHICLE (MODEL_ID)^
create index IDX_FINALPROJECT_VEHICLE_COMPLECTATION on FINALPROJECT_VEHICLE (COMPLECTATION_ID)^
-- end FINALPROJECT_VEHICLE
